server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Redirections des anciennes URLs indexées par Google vers les nouvelles URLs,
    # pour éviter que les liens référencés dans les résultats de recherche ne mènent à des pages mortes.
    location = /blog/comment-modifier-ou-retirer-le-header-server-de-nginx/ {
        return 301 /Comment-modifier-ou-retirer-le-header-server-de-nginx.html;
    }

    location = /blog/le-fichier-SBOM-Software-Bill-Of-Materials-et-pourquoi-c-est-important/ {
        return 301 /Le-fichier-SBOM-Software-Bill-Of-Materials-et-pourquoi-c-est-important.html;
    }

    location = /blog/centralisez-vos-secrets-et-configmap-kubernetes-avec-reflector/ {
        return 301 /Mutualiser-vos-secrets-et-configmap-kubernetes-avec-reflector.html;
    }

    location = /blog/migrer-de-docker-compose-vers-kubernetes-avec-kompose/ {
        return 301 /Migrer-de-Docker-Compose-vers-Kubernetes-avec-Kompose.html;
    }

    location = /blog/securiser-vos-conteneurs-avec-le-distroless/ {
        return 301 /Securiser-vos-conteneurs-avec-le-distroless.html;
    }

    location = /blog/maintenir-ses-dependances-et-conteneurs-securises-et-a-jour-avec-grype-et-trivy/ {
        return 301 /Maintenir-ses-dependances-et-conteneurs-securises-et-a-jour-avec-Grype-et-Trivy.html;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
