source "https://rubygems.org"

gem "jekyll"

group :development do
    gem 'jekyll-sitemap'
    gem 'jekyll-last-modified-at'
end

group :jekyll_plugins do
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
end
